version: '2'
services:
  web:
    build: .
    ports:
    - "80:3080"
    - "443:3443"
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules/
    environment:
      HTTP_PORT: 3080
      HTTPS_PORT: 3443
      QR_AES_ENCRYPTION_KEY: 'm7FE3kp01abm866Tr9qaAp812Vx01enP'
      MERCHANT_JWT_ACCESS_TOKEN_SECRET: "cAp81hb736nnbwI01llB23sfSbU328B1920lmnzX44bAwerlp4b7m1WEv9kUs34z"
      MERCHANT_JWT_ACCESS_TOKEN_LIFE: 1800000
      MERCHANT_JWT_REFRESH_TOKEN_SECRET: "61MlHj2i3001bvger12ui0sa8227f754huytBHS93UIvFxXa12edr03Iw47zF8o3"
      MERCHANT_JWT_REFRESH_TOKEN_LIFE: 1209600000

      CUSTOMER_JWT_ACCESS_TOKEN_SECRET: "fn81A27JMln10b4BHJ72bajk139m5m4bBAq9C7uyhi3zsD442mojpi62B7tEa2Qx"
      CUSTOMER_JWT_ACCESS_TOKEN_LIFE: 3600000
      CUSTOMER_JWT_REFRESH_TOKEN_SECRET: "61MlHj2i3001bvger12ui0sa8227f754huytBHS93UIvFxXa12edr03Iw47zF8o3"
      CUSTOMER_JWT_REFRESH_TOKEN_LIFE: 1209600000

      RDS_HOST: "jinoolee-aws-rds.c5uvkznthg94.ap-northeast-2.rds.amazonaws.com"
      RDS_USER: "etture"
      RDS_PASSWORD: "nilotkud0279"
      RDS_DATABASE: "servinggo"

      ELASTICACHE_URL: "redis://servinggo-auth-cache.4lhvlv.0001.apn2.cache.amazonaws.com:6379"

      SERVINGGO_REMOTE_API: "servinggo.app"

      NODE_ENV: "production"